### PR TITLE
Added `Coverage unchanged.` emoji

### PR DESCRIPTION
**Pull request by magnetikonline**
Just something to make it a little more obvious that you've maintained the same coverage levels. 👍

Screen Shot 2023-05-04 at 11 32 50

### CODE REVIEW

**Comment by vijay-flip** [comment]
not sur a lock is the best emoji :thinking:

**Comment by vijay-flip** [comment]
Maybe :neutral_face: ?

**Comment by dwurf** [comment]
Maybe :2nd_place_medal:

**Comment by magnetikonline** [comment]
> Maybe 🥈

@dwurf I think we have a winner - I like that, will rebase. 👍

**Comment by magnetikonline** [comment]
@dwurf done - switched for `:2nd_place_medal:`.

**Comment by danielwhite** [comment]
Have we considered _no emoji_?

**Review by dwurf — APPROVED** [review]

**Pull request merged**
